### ISSUE TITLE
Add Specta for BDD

### ISSUE THREAD

**Issue by guidomb** [Wolox/collection-view-example#2]
Add ~~[Kiwi](https://github.com/kiwi-bdd/Kiwi)~~ [Specta](https://github.com/specta/specta) for testing. Add test case for all the view models, services and categories.

**TODO LIST**
-  [x] Add spec for `ProductViewModel`
-  [ ] Add spec for `ProductCollectionViewModel`
-  [ ] Add spec for `MainViewModel`
-  [ ] Add spec for `Delegator`
-  [ ] Add spec for `ImageFetcher`
-  [ ] Add spec for `FetchAllProductFetcher`
-  [ ] Add spec for `FavoriteProductFetcher`
-  [ ] Add service to yield code coverage.
